#TODO: Rewrite

FROM oven/bun:1.1.13 AS runner

WORKDIR /app

COPY --from=builder /app/.output ./.output
COPY --from=builder /app/package.json ./
COPY --from=builder /app/bun.lock ./

RUN bun install --production

EXPOSE 3000

CMD ["bun", "run", "start"]